import type { TemplateManifest } from "./types.ts";
import { ALL_UI_SURFACES, BOTH_LOCALES, NON_CONTENT_SLOTS, contentSlots } from "./shared.ts";

export const screwfastManifest: TemplateManifest = {
  templateId: "screwfast",
  displayName: "ScrewFast / Industrial",
  manifestVersion: 1,
  runtime: "astro-static",
  nativeLocales: ["en"],
  outputLocales: BOTH_LOCALES,
  localizedUi: ALL_UI_SURFACES,
  requiredVisibleTargets: ["heroTitle"],
  slots: contentSlots({
    "hero.title": ["ScrewFast"],
    "about.body": ["ScrewFast is your trusted partner"],
    "features.items": ["Why choose ScrewFast"],
    "services.items": ["Our services"],
    products: ["Explore our products"],
    "contact.title": ["Contact Us"],
    "contact.body": ["Contact ScrewFast"],
  }),
  presentation: [
    {
      slot: "hero",
      role: "hero_split_image",
      presentAs: "首屏：左右图文分栏（左：主标题+说明+按钮；右：产品图）。标题要有产品/能力主张，说明两句内讲清范围与交付。",
      capacity: { max: 1 },
      itemShape: "title_body",
      anchor: "md:grid-cols-2 且含 h1 的首个 section",
    },
    {
      slot: "about",
      role: "split_text_media",
      presentAs: "关于：一段企业介绍正文（screwfast 原生无专门 about 区，由通用 about 生成兜底）",
      capacity: { max: 1 },
      itemShape: "title_body",
      anchor: "含 about/company 语义的 section 或无则通用",
    },
    {
      slot: "features",
      role: "icon_row",
      presentAs: "核心优势：图横幅 + 左侧标题栏 + 右侧图标+标题+正文的 2 列无边框行（icon row，非卡片）。建议 4 条（最多 6），每条标题简短。",
      capacity: { min: 2, default: 4, max: 6 },
      itemShape: "title_body",
      anchor: "含 md:grid-cols-3（左 1 栏标题 + 右 sm:grid-cols-2 icon 行）的 section；用 sm:grid-cols-2 且含 svg 的无边框行定位",
    },
    {
      slot: "services",
      role: "icon_row",
      presentAs: "服务能力：图标+标题+正文的无边框行（screwfast 用 icon row 而非卡片）。建议 3-4 条。",
      capacity: { min: 2, default: 3, max: 6 },
      itemShape: "title_body",
      anchor: "sm:grid-cols-2 且含 svg 的无边框 section（若与 features 复用同一原生区则隐藏原生区、由生成区承载）",
    },
    {
      slot: "products",
      role: "product_grid",
      presentAs: "产品中心：参数化产品条目网格（SKU/材料/规格/应用）。由通用产品网格承载。",
      capacity: { min: 1, default: 6, max: 1000 },
      itemShape: "title_body",
      anchor: "通用 renderAdditionalProducts 产品网格",
    },
    {
      slot: "contact",
      role: "split_text_media",
      presentAs: "联系：标题 + 说明 + 邮箱/电话/地址 + 询盘入口。",
      capacity: { max: 1 },
      itemShape: "title_body",
      anchor: "含 form/mailto/tel 锚的 section 或通用联系生成",
    },
  ],
  nonContentSlots: NON_CONTENT_SLOTS,
  recommendation: "eligible",
};
