import type { Template } from "@/lib/site-model";

const commonGuardrails = [
  "保留上游模板的导航、栅格、留白、字体尺度和响应式结构",
  "只修改结构化内容字段，不生成或改写 HTML、CSS、JavaScript",
  "缺失的企业事实写为“待补充”，不得虚构客户、认证、产能或经营数据",
  "主标题保持简短，行动按钮使用明确动词，并维持原模板的信息密度",
];

function prompt(
  role: string,
  structure: string[],
  visualRules: string[],
  targets: Template["promptProfile"]["targets"],
  starters: string[],
): Template["promptProfile"] {
  return {
    role,
    structure,
    visualRules,
    targets,
    guardrails: commonGuardrails,
    starters,
  };
}

const heroTargets = (
  titleGuidance: string,
  subtitleGuidance: string,
): Template["promptProfile"]["targets"] => [
  { key: "brand", label: "品牌名称", guidance: "使用客户正式企业简称，避免口号化命名" },
  { key: "heroTitle", label: "首屏标题", guidance: titleGuidance },
  { key: "heroSubtitle", label: "首屏说明", guidance: subtitleGuidance },
  { key: "primaryCta", label: "主行动按钮", guidance: "使用查看产品、预约演示、获取方案或提交需求等明确动作" },
  { key: "products", label: "产品与能力", guidance: "优先使用已导入商品，不存在的数据标记待补充" },
  { key: "about", label: "关于我们", guidance: "只使用客户提供的企业事实，缺失信息明确标记待补充" },
  { key: "features", label: "核心优势", guidance: "将客户价值拆成可扫描的标题和说明" },
  { key: "services", label: "服务模块", guidance: "按服务步骤或能力模块组织标题与说明" },
  { key: "contact", label: "联系模块", guidance: "保持联系方式准确并提供明确询盘入口" },
];

export const templateCatalog: Template[] = [
  {
    id: "forge",
    name: "SMALL BIS / Small Business",
    category: "制造业",
    description: "留白充足、产品优先的轻量企业官网，适合制造与本地企业。",
    tags: ["工业制造", "产品目录", "清爽留白"],
    colors: { primary: "#194c38", secondary: "#e7f1e2", accent: "#d3f37c" },
    headline: "Built for the\nnext standard.",
    subtitle: "From material intelligence to production certainty.",
    source: { name: "Small Bis", repoUrl: "https://github.com/Dillonpw/small-bis", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://small-bis.vercel.app/", localPath: "vendor/open-source-templates/small-bis" },
    promptProfile: prompt(
      "工业企业内容架构师，强调可靠性、产品能力与直接询盘",
      ["简洁导航", "产品导向 Hero", "核心服务", "信任信息", "联系 CTA"],
      ["保留明亮背景与绿色强调", "标题不超过两行", "产品信息先于企业故事"],
      heroTargets("用一个可验证的制造能力或客户价值作标题", "用两句以内说明产品范围、应用场景和交付价值"),
      ["把首屏改成精密零部件出口企业", "突出三项核心制造能力", "把 CTA 改为获取产品目录"],
    ),
  },
  {
    id: "atlas",
    name: "ASTROPLATE / Business",
    category: "外贸目录",
    description: "内容层次完整的多页面商业模板，适合全球业务与内容型官网。",
    tags: ["全球贸易", "多页面", "双语官网"],
    colors: { primary: "#203b62", secondary: "#e5eff8", accent: "#f0bf5b" },
    headline: "Move products\nacross borders.",
    subtitle: "A clear global catalog for ambitious teams.",
    source: { name: "Astroplate", repoUrl: "https://github.com/zeon-studio/astroplate", license: "MIT", framework: "Astro + Tailwind + TypeScript", demoUrl: "https://astroplate.netlify.app/", localPath: "vendor/open-source-templates/astroplate" },
    promptProfile: prompt(
      "B2B 外贸官网策划师，组织多语言产品、市场和询盘路径",
      ["居中 Hero", "品牌信任", "产品分类", "内容/新闻", "全球联系"],
      ["保持居中、宽屏的商业版式", "中英文标题长度接近", "首页最多突出三类产品"],
      heroTargets("说明出口品类、目标市场或供应优势", "补充服务地区、品控方式与合作对象，未知数据写待补充"),
      ["面向欧美采购商重写首页", "把导入商品整理成三大分类", "生成中英文一致的询盘 CTA"],
    ),
  },
  {
    id: "signal",
    name: "RICOFAST / SaaS",
    category: "科技企业",
    description: "明快的 SaaS 营销页面，擅长功能、流程和转化表达。",
    tags: ["B2B 科技", "SaaS", "产品能力"],
    colors: { primary: "#34256a", secondary: "#eeeafe", accent: "#d9f36b" },
    headline: "Make complexity\nuseful.",
    subtitle: "Technology that turns dense signals into decisive action.",
    source: { name: "RicoFast", repoUrl: "https://github.com/ricocc/ricoui-saas-template", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://ricofast.pages.dev/", localPath: "vendor/open-source-templates/ricofast" },
    promptProfile: prompt(
      "SaaS 增长文案编辑，先讲用户结果，再解释技术能力",
      ["产品价值 Hero", "客户信任", "功能网格", "工作流程", "转化 CTA"],
      ["保留高对比科技配色", "功能标题使用动词", "避免堆砌 AI、智能化等空泛词"],
      heroTargets("用具体业务结果而不是技术名词开场", "说明适用团队、核心流程和可衡量价值"),
      ["为供应链 SaaS 重写价值主张", "按用户工作流程组织功能", "把 CTA 改成预约产品演示"],
    ),
  },
  {
    id: "kindred",
    name: "ODYSSEY / Business Theme",
    category: "专业服务",
    description: "沉稳的编辑式商业主题，适合咨询、工程和专业服务机构。",
    tags: ["咨询服务", "案例展示", "编辑风格"],
    colors: { primary: "#6e3e2d", secondary: "#f6ebe2", accent: "#edb48b" },
    headline: "Good work,\nmade visible.",
    subtitle: "A considered digital home for teams people trust.",
    source: { name: "Odyssey Theme", repoUrl: "https://github.com/treefarmstudio/odyssey-theme", license: "MIT", framework: "Astro", demoUrl: "https://odyssey-theme.sapling.supply/", localPath: "vendor/open-source-templates/odyssey" },
    promptProfile: prompt(
      "专业服务品牌编辑，用观点、方法与案例建立可信度",
      ["编辑式 Hero", "服务方法", "精选案例", "团队/观点", "咨询 CTA"],
      ["保留克制的编辑排版", "避免营销夸张词", "案例必须基于客户提供事实"],
      heroTargets("表达机构立场和最擅长解决的问题", "解释服务对象、工作方法与合作结果"),
      ["改成工程咨询公司官网", "突出三阶段服务方法", "用更克制可信的语气重写"],
    ),
  },
  {
    id: "powerai",
    name: "GENAI / AI Company",
    category: "科技企业",
    description: "专为 AI 产品与开发者工具准备的深色多页面主题。",
    tags: ["AI 产品", "开发者工具", "案例博客"],
    colors: { primary: "#151e38", secondary: "#e5eafe", accent: "#9de7ff" },
    headline: "Build what\ncomes next.",
    subtitle: "A launch-ready foundation for ambitious AI products.",
    source: { name: "Generative AI Company Theme", repoUrl: "https://github.com/ctrimm/astro-genai-startup-theme", license: "MIT", framework: "Astro + React + Tailwind", demoUrl: "https://ctrimm.github.io/astro-genai-startup-theme/", localPath: "vendor/open-source-templates/genai" },
    promptProfile: prompt(
      "AI 产品营销负责人，把模型能力翻译为真实工作场景和安全边界",
      ["AI 产品 Hero", "应用场景", "能力模块", "案例/资源", "演示 CTA"],
      ["保留深色未来感和高亮强调", "技术能力需对应业务场景", "不宣称未提供的模型指标"],
      heroTargets("一句话说明 AI 为谁完成什么任务", "说明接入方式、典型场景与差异化能力"),
      ["改成企业知识库 AI 助手", "突出安全部署和权限管理", "为开发者受众优化首屏"],
    ),
  },
  {
    id: "landwind",
    name: "LANDWIND / Clean",
    category: "外贸目录",
    description: "Flowbite 风格的成熟落地页，结构清晰且转化组件完整。",
    tags: ["响应式", "产品介绍", "清晰转化"],
    colors: { primary: "#1d4ed8", secondary: "#e0ecff", accent: "#f7c85c" },
    headline: "Move your\nbusiness forward.",
    subtitle: "A clean, responsive foundation for modern teams.",
    source: { name: "Landwind", repoUrl: "https://github.com/themesberg/landwind", license: "MIT", framework: "Tailwind + Flowbite", demoUrl: "https://demo.themesberg.com/landwind/", localPath: "vendor/open-source-templates/landwind" },
    promptProfile: prompt(
      "转化型企业落地页编辑，保持信息直接、模块完整、行动清晰",
      ["左右分栏 Hero", "品牌 Logo", "功能说明", "数据/评价", "价格或询盘 CTA"],
      ["保持蓝白清晰层级", "每个功能点不超过两句", "无报价信息时将价格区改为询盘"],
      heroTargets("直接说明产品类别和首要价值", "用客户能理解的语言解释用途和适用场景"),
      ["改成工业设备出口落地页", "移除定价语气改为询盘", "把产品优势整理成六项"],
    ),
  },
  {
    id: "lonestone",
    name: "ASTROWIND / Business",
    category: "专业服务",
    description: "成熟的多页面企业主题，兼顾服务、内容与博客。",
    tags: ["企业营销", "博客", "多页面"],
    colors: { primary: "#31363d", secondary: "#edf0f2", accent: "#f2a65a" },
    headline: "Make knowledge\nuseful.",
    subtitle: "A considered home for products, services and ideas.",
    source: { name: "AstroWind", repoUrl: "https://github.com/arthelokyo/astrowind", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://astrowind.vercel.app/", localPath: "vendor/open-source-templates/astrowind" },
    promptProfile: prompt(
      "内容型企业网站主编，统一服务页、案例和长期内容栏目",
      ["双栏 Hero", "核心服务", "价值说明", "文章/案例", "联系 CTA"],
      ["保持成熟中性的商业风格", "将长内容分成可扫描的小节", "文章标题避免广告腔"],
      heroTargets("概括企业专长与长期价值", "用一段话连接服务、客户问题和内容资产"),
      ["改成技术咨询公司内容官网", "规划服务与博客栏目", "让首屏更专业、更少营销味"],
    ),
  },
  {
    id: "astro-starter",
    name: "TAILCAST / Startup",
    category: "科技企业",
    description: "现代深色 SaaS 模板，适合产品发布、功能说明和获客。",
    tags: ["科技公司", "产品发布", "SaaS"],
    colors: { primary: "#174c4f", secondary: "#e0f1ef", accent: "#f2c14e" },
    headline: "Your work,\ncloser to home.",
    subtitle: "A focused starting point for product-led teams.",
    source: { name: "Tailcast", repoUrl: "https://github.com/matt765/Tailcast", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://tailcast.vercel.app/", localPath: "vendor/open-source-templates/tailcast" },
    promptProfile: prompt(
      "产品发布页编辑，用紧凑节奏呈现价值、功能和注册路径",
      ["深色 Hero", "产品截图", "功能卡片", "工作方式", "开始使用 CTA"],
      ["保留深色背景和亮色 CTA", "首屏仅保留一个主行动", "功能文案强调使用结果"],
      heroTargets("用清晰的产品承诺吸引目标用户", "说明产品解决的核心任务以及开始方式"),
      ["改成团队协作 SaaS", "把功能按使用场景重排", "将 CTA 优化为申请试用"],
    ),
  },
  {
    id: "awesome",
    name: "AWESOME / Landing",
    category: "专业服务",
    description: "模块化 Astro 落地页，适合快速组织服务亮点和行动入口。",
    tags: ["模块化", "服务展示", "轻量快速"],
    colors: { primary: "#161616", secondary: "#f3f3f3", accent: "#ffcf4a" },
    headline: "A focused idea,\nclearly presented.",
    subtitle: "A modular landing page for focused service offers.",
    source: { name: "Astro Landing Page", repoUrl: "https://github.com/ttntm/astro-landing-page", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://ttntm.github.io/astro-landing-page/", localPath: "vendor/open-source-templates/awesome" },
    promptProfile: prompt(
      "单一服务落地页策划师，围绕一个受众和一个转化目标组织内容",
      ["集中式 Hero", "利益点", "服务步骤", "证明信息", "单一 CTA"],
      ["保持模块简洁和强对比", "一个页面只保留一个主要转化目标", "删除重复价值表述"],
      heroTargets("只表达一个核心服务承诺", "说明受众、交付内容和下一步行动"),
      ["改成企业出海咨询落地页", "围绕预约咨询重组内容", "将优势压缩成三个要点"],
    ),
  },
  {
    id: "astrofy",
    name: "ASTROFY / Portfolio",
    category: "专业服务",
    description: "个人与工作室作品集模板，以项目、经历和专业能力为核心。",
    tags: ["作品集", "工作室", "个人品牌"],
    colors: { primary: "#202020", secondary: "#f5f5f5", accent: "#4f7cff" },
    headline: "Selected work,\nwith a clear point of view.",
    subtitle: "A portfolio for specialists and small creative teams.",
    source: { name: "Astrofy", repoUrl: "https://github.com/manuelernestog/astrofy", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://astrofy-template.netlify.app/", localPath: "vendor/open-source-templates/astrofy" },
    promptProfile: prompt(
      "专业作品集编辑，以项目证据、角色和方法展示能力",
      ["个人/工作室简介", "精选项目", "经历与技能", "关于", "联系"],
      ["让项目成为页面主角", "每个案例写清职责和结果", "没有真实项目时使用待补充占位"],
      heroTargets("说明身份、专长和服务对象", "简述工作方法和最值得查看的项目类型"),
      ["改成工业设计工作室作品集", "按行业整理项目", "让个人简介更简练专业"],
    ),
  },
  {
    id: "astropaper",
    name: "ASTROPAPER / Knowledge",
    category: "专业服务",
    description: "阅读体验优先的极简内容模板，适合专家、研究和企业知识库。",
    tags: ["博客", "知识内容", "阅读体验"],
    colors: { primary: "#1e293b", secondary: "#f8fafc", accent: "#f59e0b" },
    headline: "Ideas worth\nkeeping clear.",
    subtitle: "A fast, accessible home for durable knowledge.",
    source: { name: "AstroPaper", repoUrl: "https://github.com/satnaing/astro-paper", license: "MIT", framework: "Astro + TypeScript", demoUrl: "https://astro-paper.pages.dev/", localPath: "vendor/open-source-templates/astropaper" },
    promptProfile: prompt(
      "企业知识内容主编，优先保证可读性、分类和长期检索价值",
      ["站点简介", "最新文章", "主题分类", "文章详情", "订阅/联系"],
      ["保留纯净阅读版式", "标题准确描述文章问题", "摘要控制在两句话"],
      heroTargets("概括内容领域和读者收益", "说明更新范围、专业背景与内容边界"),
      ["改成工业自动化知识中心", "规划四个内容分类", "把首页介绍改得更像专业出版物"],
    ),
  },
  {
    id: "moon",
    name: "MOON / Product Launch",
    category: "科技企业",
    description: "精炼的 Astro 产品落地页，以发布节奏和功能说明见长。",
    tags: ["产品发布", "功能展示", "现代简约"],
    colors: { primary: "#111827", secondary: "#eef2ff", accent: "#7c3aed" },
    headline: "Launch with\nless noise.",
    subtitle: "A concise product story from problem to action.",
    source: { name: "Moon Landing Page", repoUrl: "https://github.com/mhyfritz/astro-landing-page", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://astro-moon-landing.netlify.app/", localPath: "vendor/open-source-templates/moon" },
    promptProfile: prompt(
      "精简型产品发布编辑，删除噪音并建立问题到行动的短路径",
      ["极简 Hero", "核心功能", "使用场景", "产品证明", "注册 CTA"],
      ["保持大量留白", "标题不超过八个中文字或六个英文词", "功能段落保持短小"],
      heroTargets("用最短句子表达产品改变", "补充目标用户、核心任务和差异点"),
      ["改成数据分析工具发布页", "把内容压缩到一个屏幕重点", "让 CTA 更明确"],
    ),
  },
  {
    id: "astrogent",
    name: "ASTROGENT / Agency",
    category: "专业服务",
    description: "视觉强烈的创意机构模板，适合品牌、数字与设计服务团队。",
    tags: ["创意机构", "服务案例", "品牌表达"],
    colors: { primary: "#111111", secondary: "#f5f1e8", accent: "#e94f37" },
    headline: "Work that makes\na clear difference.",
    subtitle: "A bold agency presentation built around proof and personality.",
    source: { name: "Astrogent", repoUrl: "https://github.com/fauziralpiandi/astrogent", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://astrogent.vercel.app/", localPath: "vendor/open-source-templates/astrogent" },
    promptProfile: prompt(
      "创意机构品牌编辑，用鲜明观点、代表案例和服务方法形成记忆点",
      ["宣言式 Hero", "服务范围", "重点案例", "工作方法", "项目咨询"],
      ["保留大胆字号和节奏", "案例描述先写挑战再写贡献", "不要用无证据的行业第一"],
      heroTargets("写成有立场的品牌宣言，但必须可理解", "说明机构帮助谁、解决什么品牌或增长问题"),
      ["改成 B2B 品牌设计机构", "突出三个代表项目", "把语气改得大胆但不浮夸"],
    ),
  },
  {
    id: "devportfolio",
    name: "DEVPORTFOLIO / Profile",
    category: "科技企业",
    description: "经典开发者作品集，集中呈现技能、项目与职业经历。",
    tags: ["开发者", "项目履历", "技术品牌"],
    colors: { primary: "#0f172a", secondary: "#f1f5f9", accent: "#38bdf8" },
    headline: "Engineering,\nmade tangible.",
    subtitle: "Projects, experience and technical strengths in one clear profile.",
    source: { name: "DevPortfolio", repoUrl: "https://github.com/RyanFitzgerald/devportfolio", license: "MIT", framework: "HTML + Sass + JavaScript", demoUrl: "https://ryanfitzgerald.github.io/devportfolio", localPath: "vendor/open-source-templates/devportfolio" },
    promptProfile: prompt(
      "技术人才与研发工作室履历编辑，用项目和责任范围证明能力",
      ["身份 Hero", "关于", "工作经历", "项目", "技能与联系"],
      ["保留单页时间线结构", "项目写清技术、职责和结果", "未提供的雇主或结果不得补造"],
      heroTargets("说明技术角色、方向与可承接工作", "用事实概述经验范围和代表性能力"),
      ["改成 AI 工程师作品集", "按影响力重排项目", "把经历描述改得更具体"],
    ),
  },
  {
    id: "foxi",
    name: "FOXI / SaaS Suite",
    category: "科技企业",
    description: "页面与组件丰富的 SaaS 主题，适合复杂产品线和增长内容。",
    tags: ["SaaS 套件", "多页面", "增长转化"],
    colors: { primary: "#312e81", secondary: "#eef2ff", accent: "#22d3ee" },
    headline: "One product story,\nevery path covered.",
    subtitle: "A complete SaaS suite for products with more to explain.",
    source: { name: "Foxi Astro Theme", repoUrl: "https://github.com/oxygenna-themes/foxi-astro-theme", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://foxi.netlify.app/", localPath: "vendor/open-source-templates/foxi" },
    promptProfile: prompt(
      "复杂 SaaS 信息架构师，在多页面中统一产品、方案、资源和转化",
      ["产品 Hero", "能力矩阵", "解决方案", "客户证明", "资源", "演示 CTA"],
      ["保持组件丰富但避免重复", "按客户任务而非内部部门分类", "只保留与当前产品相关的页面"],
      heroTargets("概括整个产品套件带来的业务改变", "解释主要模块、使用对象和落地方式"),
      ["改成企业数据中台官网", "为三类客户规划解决方案页", "精简首页重复模块"],
    ),
  },
  {
    id: "yukina",
    name: "YUKINA / Editorial Blog",
    category: "专业服务",
    description: "精致的内容与博客主题，适合品牌杂志、团队动态和专业观点。",
    tags: ["品牌内容", "博客杂志", "文章归档"],
    colors: { primary: "#263238", secondary: "#f7f7f5", accent: "#d97706" },
    headline: "A living record\nof useful work.",
    subtitle: "An editorial home for company insight, news and field notes.",
    source: { name: "Yukina", repoUrl: "https://github.com/WhitePaper233/yukina", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://yukina-blog.vercel.app", localPath: "vendor/open-source-templates/yukina" },
    promptProfile: prompt(
      "品牌杂志主编，将企业新闻、案例和专业观点组织成持续更新的内容产品",
      ["编辑推荐", "最新内容", "主题分类", "文章详情", "品牌信息"],
      ["保留杂志式层级和图片节奏", "新闻与观点明确区分", "日期、作者和事实必须来自输入"],
      heroTargets("概括品牌内容主题而非直接销售", "说明读者会获得哪些新闻、案例或专业知识"),
      ["改成制造企业品牌杂志", "建立新闻、案例和技术洞察栏目", "重写首页导语但不要营销化"],
    ),
  },
  {
    id: "fresh",
    name: "FRESH / SaaS Landing",
    category: "科技企业",
    description: "现代深色 SaaS 落地页，强调产品界面、功能与转化。",
    tags: ["SaaS", "深色现代", "产品界面"],
    colors: { primary: "#0f0f23", secondary: "#181832", accent: "#6d5ef2" },
    headline: "Ship the next\nstandard.",
    subtitle: "A bold, dark SaaS foundation built for product-led teams.",
    source: { name: "Fresh", repoUrl: "https://github.com/cssninjaStudio/fresh", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://fresh.cssninja.io/", localPath: "vendor/open-source-templates/fresh" },
    promptProfile: prompt(
      "SaaS 产品营销编辑，把产品界面、功能与客户结果放在最前",
      ["产品价值 Hero", "产品界面展示", "功能网格", "客户证明", "转化 CTA"],
      ["保留深色高对比视觉", "产品截图优先于抽象描述", "功能标题使用业务结果动词"],
      heroTargets("用可衡量的产品结果开场", "说明核心功能、适用团队与落地路径"),
      ["改成数据可视化 SaaS 官网", "把首屏改成产品界面演示", "为开发者受众组织功能模块"],
    ),
  },
  {
    id: "shadcn-landing",
    name: "SHADCN / Modern Landing",
    category: "科技企业",
    description: "基于 shadcn/ui 的现代浅色落地页，组件完整、风格克制。",
    tags: ["shadcn/ui", "现代浅色", "开发者友好"],
    colors: { primary: "#18181b", secondary: "#fafafa", accent: "#6d28d9" },
    headline: "Build what\nusers feel.",
    subtitle: "A calm, component-driven landing page for modern software teams.",
    source: { name: "Shadcn Landing Page", repoUrl: "https://github.com/leoMirandaa/shadcn-landing-page", license: "MIT", framework: "Next.js + shadcn/ui + Tailwind", demoUrl: "https://shadcn-landing-page.vercel.app/", localPath: "vendor/open-source-templates/shadcn-landing" },
    promptProfile: prompt(
      "开发者工具营销编辑，用克制的设计语言讲清楚产品价值",
      ["产品价值 Hero", "功能特性", "使用流程", "技术集成", "转化 CTA"],
      ["保留浅色高对比与精确排版", "功能描述避免夸大", "集成说明突出技术细节"],
      heroTargets("一句话说明开发者工具解决什么问题", "补充使用场景、集成方式与差异化"),
      ["改成开发者 API 工具官网", "把功能按使用场景重排", "为首屏加一段真实代码示例"],
    ),
  },
  {
    id: "screwfast",
    name: "SCREWFAST / Industrial",
    category: "制造业",
    description: "为制造与工业企业设计的 Astro 模板，强调产品线、应用场景与工程可信度。",
    tags: ["工业制造", "产品线", "工程可信"],
    colors: { primary: "#1f3a5f", secondary: "#eef2f7", accent: "#f2a33c" },
    headline: "Engineered to\nperform.",
    subtitle: "Precision products, proven in the field.",
    source: { name: "ScrewFast", repoUrl: "https://github.com/mearashadowfax/ScrewFast", license: "MIT", framework: "Astro + Tailwind", demoUrl: "https://screwfast.uk/", localPath: "vendor/open-source-templates/screwfast" },
    promptProfile: prompt(
      "工业企业官网架构师，强调产品线、应用场景与工程可信度",
      ["产品导向 Hero", "核心产品线", "应用场景", "工程优势", "联系 CTA"],
      ["保留工业蓝灰配色与金属感", "产品信息先于企业故事", "突出认证与质量体系"],
      heroTargets("用可验证的产品能力或工程价值作标题", "用两句以内说明产品范围、应用场景与交付能力"),
      ["把首屏改成高精度轴承制造商", "突出三大核心产品线", "把 CTA 改为获取产品样本"],
    ),
  },
  {
    id: "tailwind-landing",
    name: "TAILWIND LANDING / Business",
    category: "外贸目录",
    description: "纯 Tailwind 的多用途企业落地页，简洁、响应式、转化组件完整。",
    tags: ["落地页", "多用途", "Tailwind"],
    colors: { primary: "#1f2937", secondary: "#f9fafb", accent: "#f59e0b" },
    headline: "Take the\nnext step.",
    subtitle: "A clear, responsive landing page for businesses going further.",
    source: { name: "Tailwind Landing", repoUrl: "https://github.com/tailwindtoolbox/Landing-Page", license: "MIT", framework: "HTML + Tailwind", demoUrl: "https://tailwindtoolbox.github.io/Landing-Page", localPath: "vendor/open-source-templates/tailwind-landing" },
    promptProfile: prompt(
      "多用途企业落地页编辑，保持信息直接、模块完整、行动清晰",
      ["左右分栏 Hero", "功能说明", "数据/评价", "价格或询盘 CTA", "联系"],
      ["保持 Tailwind 清晰层级", "功能点不超过两句", "无报价信息时将价格区改为询盘"],
      heroTargets("直接说明产品类别和首要价值", "用客户能理解的语言解释用途和适用场景"),
      ["改成工业设备出口落地页", "移除定价语气改为询盘", "把产品优势整理成六项"],
    ),
  },
  {
    id: "nextjs-landing",
    name: "NEXT LANDING / Corporate",
    category: "专业服务",
    description: "开发者优先的 Next.js 企业落地页，结构清晰、适合内容型官网。",
    tags: ["Next.js", "企业官网", "开发者友好"],
    colors: { primary: "#2563eb", secondary: "#eef4ff", accent: "#f59e0b" },
    headline: "Clarity for\nyour next move.",
    subtitle: "A focused, developer-friendly home for teams with something to say.",
    source: { name: "Next.js Landing Starter", repoUrl: "https://github.com/ixartz/Next-JS-Landing-Page-Starter-Template", license: "MIT", framework: "Next.js + Tailwind", demoUrl: "https://creativedesignsguru.com", localPath: "vendor/open-source-templates/nextjs-landing" },
    promptProfile: prompt(
      "企业官网编辑，用清晰的层级讲好服务、观点与专业能力",
      ["双栏 Hero", "核心服务", "价值说明", "案例/观点", "联系 CTA"],
      ["保持成熟中性的商业风格", "将长内容分成可扫描的小节", "标题避免广告腔"],
      heroTargets("概括企业专长与长期价值", "用一段话连接服务、客户问题和内容资产"),
      ["改成技术咨询公司内容官网", "规划服务与博客栏目", "让首屏更专业、更少营销味"],
    ),
  },
  {
    id: "shadcn-landing2",
    name: "SHADCN PRO / Modern",
    category: "科技企业",
    description: "基于 shadcn/ui 的现代落地页，组件丰富、风格克制、适合开发者工具。",
    tags: ["shadcn/ui", "现代浅色", "开发者工具"],
    colors: { primary: "#111827", secondary: "#f8fafc", accent: "#6366f1" },
    headline: "Build the\nnext thing.",
    subtitle: "A calm, component-driven landing page for modern software teams.",
    source: { name: "Shadcn Landing (Pro)", repoUrl: "https://github.com/nobruf/shadcn-landing-page", license: "MIT", framework: "Next.js + shadcn/ui + Tailwind", demoUrl: "https://shadcn-landing-page-livid.vercel.app", localPath: "vendor/open-source-templates/shadcn-landing2" },
    promptProfile: prompt(
      "开发者工具营销编辑，用克制的设计语言讲清楚产品价值",
      ["产品价值 Hero", "功能特性", "使用流程", "技术集成", "转化 CTA"],
      ["保留浅色高对比与精确排版", "功能描述避免夸大", "集成说明突出技术细节"],
      heroTargets("一句话说明开发者工具解决什么问题", "补充使用场景、集成方式与差异化"),
      ["改成开发者 API 工具官网", "把功能按使用场景重排", "为首屏加一段真实代码示例"],
    ),
  },
];
